package com.epau.lib.swing.wizard.page;

import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;

public class PageFrame extends JFrame {

	private JPanel        content;
	private PageTitleList pageTitleList;
	private JPanel        pageContent;
	private ButtonBar     buttonBar;
	private JLabel        pageDescription;
	private JScrollPane   pageTitleListScrollPane;

	public PageFrame(String title) {
		$$$setupUI$$$();
		setTitle(title);
		setContentPane(content);
	}

	private void createUIComponents() {
		pageTitleListScrollPane = new JScrollPane();
		pageTitleListScrollPane.getViewport().setBackground(Color.WHITE);
		pageTitleListScrollPane.setBackground(Color.WHITE);
		pageTitleListScrollPane.setViewportBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
		pageTitleList = new PageTitleList();

		// page title list is note yet filled, that is why we have to set dimensions
		pageTitleListScrollPane.setPreferredSize(new Dimension(100, 0));
		pageTitleListScrollPane.setMinimumSize(new Dimension(100, 0));
		pageTitleListScrollPane.setMinimumSize(pageTitleListScrollPane.getPreferredSize());
		pageTitleList.setBackground(Color.WHITE);
	}

	void showPage(Page page) {
		pageDescription.setText(page.getDescription());
		pageContent.removeAll();
		pageContent.add(page.getContent());
		pageContent.revalidate();
		pageContent.repaint();
	}

	public PageTitleList getPageTitleList() {
		return pageTitleList;
	}

	public ButtonBar getButtonBar() {
		return buttonBar;
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		content = new JPanel();
		content.setLayout(new GridBagLayout());
		pageDescription = new JLabel();
		pageDescription.setText("<Description>");
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.insets = new Insets(10, 10, 10, 10);
		content.add(pageDescription, gbc);
		final JSeparator separator1 = new JSeparator();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.BOTH;
		content.add(separator1, gbc);
		pageContent = new JPanel();
		pageContent.setLayout(new BorderLayout(0, 0));
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 2;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		content.add(pageContent, gbc);
		buttonBar = new ButtonBar();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 4;
		gbc.gridwidth = 2;
		gbc.weightx = 1.0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		gbc.insets = new Insets(10, 10, 10, 10);
		content.add(buttonBar, gbc);
		final JSeparator separator2 = new JSeparator();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.gridwidth = 2;
		gbc.fill = GridBagConstraints.BOTH;
		content.add(separator2, gbc);
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridheight = 4;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		gbc.ipadx = 50;
		gbc.ipady = 50;
		content.add(pageTitleListScrollPane, gbc);
		pageTitleList.setEnabled(false);
		final DefaultListModel defaultListModel1 = new DefaultListModel();
		pageTitleList.setModel(defaultListModel1);
		pageTitleList.setValueIsAdjusting(false);
		pageTitleListScrollPane.setViewportView(pageTitleList);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() { return content; }

}
